spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    foo: foo.t

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: debug
server:
  port: 18003
  servlet:
    context-path: /api


test:
  name: yuankk
